### ISSUE TITLE
ERS-018 New messages don't appear unless user manually refreshes page

### ISSUE THREAD

**Issue by dougzytko** [markovLabs/eros#33] opened 2017-08-15 21:12 UTC
For conversations 2-8, new messages that a user sends/receives are not visible unless they manually hit the refresh button (e.g. if I send a message, it doesn't show up in the conversation for either user until they hit the refresh button). This issue does not apply to the first round of conversation.

**Comment by vrrs** [comment] 2017-08-15 21:49
Duplicate of ERS-007

**Closed as completed by vrrs** 2017-08-15 21:49 UTC
Labels: duplicate
